# Generated by Django 5.2.8 on 2025-11-19 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_candidate_emailotp_recruiter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='last_name',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='first_name',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='recruiter',
            old_name='last_name',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='recruiter',
            old_name='first_name',
            new_name='username',
        ),
    ]
